Repository HenryBcit/classDAISetA, pull requests merged in 2019-09, with the labels that each got.

#5 First file
  Shenis/index.js
Labels: help wanted, question

#18 Initial commit
  Julie/index.js
Labels: bug, help wanted, question

#19 i am bread
  Elias/index.html
Labels: APPROVE ME

#2 first file
  Cynthia/index.html
Labels: bug

#16 haha
  Tin/index.js
Labels: bug, documentation, duplicate, enhancement, good first issue, help wanted, invalid, question, wontfix

#11 First File
  Kaan/index.js
Labels: bug

#4 First File
  Monika/index.js
Labels: bug, help wanted
